config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  root 'pages#index'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'dashboard', to: 'pages#dashboard'

  get 'auth/:provider', to: ->(env){ [404, {}, ['Not Found']] }, as: 'auth'
  get 'auth/:provider/callback', to: 'sessions#create', as: 'auth_callback'
  get 'logout', to: 'sessions#destroy'

  get 'playlists', to: 'playlists#index'
  get 'playlists/refresh', to: 'playlists#refresh_index'
  get 'playlist/:spotify_id', to: 'playlists#show', as: 'playlist'
  get 'playlist/:spotify_id/refresh', to: 'playlists#refresh', as: 'playlist_refresh'

  mount Sidekiq::Web => '/sidekiq'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :playlist
  belongs_to :track

  validates :playlist_id, :track_id, :position, presence: true
  # The position is unique within a given Playlist
  validates :position, uniqueness: { scope: :playlist_id }
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  has_many :user_playlists
  has_many :users, through: :user_playlists
  has_many :entries
  has_many :tracks, through: :entries

  validates :spotify_id, presence: true, uniqueness: true
  validates :owner_id, presence: true

  def spotify_playlist
    RSpotify::Playlist.find(owner_id, spotify_id)
  end
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  belongs_to :template
end

app/models/template.rb
class Template < ActiveRecord::Base
  belongs_to :user
  belongs_to :playlist
  has_many :rules
end

app/models/track.rb
class Track < ActiveRecord::Base
  has_many :entries
  has_many :playlists, through: :entries

  validates :spotify_id, presence: true, uniqueness: true

  def spotify_track
    RSpotify::Track.find(spotify_id)
  end
end

app/models/user.rb
require 'upsert/active_record_upsert'

class User < ActiveRecord::Base
  has_many :user_playlists
  has_many :playlists, through: :user_playlists
  has_many :tracks, through: :playlists

  serialize :spotify_auth

  validates :spotify_id, presence: true, uniqueness: true
  validates :spotify_auth, presence: true

  def self.upsert_with_auth(auth)
    spotify_user = RSpotify::User.new(auth)
    timestamp = UpsertHelper.timestamp
    User.upsert({spotify_id: spotify_user.id}, spotify_auth: auth.to_yaml,
      name: spotify_user.display_name, email: spotify_user.email,
      created_at: timestamp, updated_at: timestamp)
    # Return the User
    User.find_by(spotify_id: spotify_user.id)
  end

  def spotify_user
    RSpotify::User.new(spotify_auth)
  end
end

app/models/user_playlist.rb
class UserPlaylist < ActiveRecord::Base
  belongs_to :user
  belongs_to :playlist
  has_many :entries, through: :playlist

  validates :user_id, :playlist_id, :position, presence: true
  # A playlist is unique for a given User
  validates :playlist_id, uniqueness: { scope: :user_id }
  # The positions are unique for a given User
  validates :position, uniqueness: { scope: :user_id }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?, :authenticate_user!

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def signed_in?
    current_user != nil
  end

  def authenticate_user!
    redirect_to root_path, notice: 'Please sign in first.' unless signed_in?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def dashboard
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_playlist, only: [:show, :refresh]

  def index
    @playlists = current_user.playlists
  end

  def refresh_index
    UserPlaylistsJob.perform_now(current_user)
    redirect_to playlists_path, notice: "Your playlist index is being reloaded"
  end

  def show
    EntriesJob.perform_now(@playlist)
    @entries = Entry.includes(:track).order(position: :asc).where(playlist: @playlist)
  end

  def refresh
    EntriesJob.perform_now(@playlist)
    redirect_to playlists_path, notice: "\"#{@playlist.name}\" is being reloaded"
  end

  private

  def set_playlist
    #@user_playlist = UserPlaylist.includes(:playlist).find_by(user: current_user,
    #  playlists: { spotify_id: params[:spotify_id] })
    #@playlist = @user_playlist.playlist
    @playlist = Playlist.find_by(spotify_id: params[:spotify_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def playlist_params
    params[:playlist]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.upsert_with_auth(request.env['omniauth.auth'])
    # Asynchronously refresh the user's playlists
    UserPlaylistsJob.perform_now(user)
    session[:user_id] = user.id
    redirect_to dashboard_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Signed out!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/upsert_helper.rb
module UpsertHelper
  def self.timestamp
    Time.now.utc.strftime('%Y-%m-%d %H:%M:%S.%6N')
  end
end

app/views/layouts/_footer.html.haml
%footer
  %p &copy; 2015 Musiquely

app/views/layouts/_header.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Musiquely", root_path, class: "navbar-brand"
    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-left
        %li= link_to "Blog", "http://blog.musiquely.com/"
        %li= link_to "About", about_path
        %li= link_to "Contact", contact_path
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "Register", root_path
        %li= link_to "Sign In", root_path

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{'data-target' => '#navbar-collapse', 'data-toggle' => 'collapse', type: 'button'}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Musiquely', root_path, class: 'navbar-brand'
    #navbar-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-left
        %li= link_to 'About', about_path
        %li= link_to 'Contact', contact_path
      %ul.nav.navbar-nav.navbar-right
        - if current_user
          %li= link_to 'Dashboard', dashboard_path
          %li= link_to 'Log out', logout_path
        - else
          %li= link_to 'Sign in with Spotify', auth_path('spotify')

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Musiquely
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      = yield
      = render 'layouts/footer'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}
    %title Musiquely
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render 'layouts/header'
    .container
      - flash.each do |name, msg|
        .alert.alert-info.alert-dismissible{role: 'alert'}
          %button.close{type: 'button', 'data-dismiss' => 'alert', 'aria-label' => 'Close'}
            %span{'aria-hidden' => 'true'} &times;
          = msg
      = yield
      %hr
      = render 'layouts/footer'

app/views/pages/about.haml
%h1 About
%p Musiquely is a cloud based playlist management service. We are currently in development, stay tuned.

app/views/pages/about.html.haml
%h1 About
%p Musiquely is a cloud based playlist management service. We are currently in development, stay tuned.

app/views/pages/contact.haml
%h1 Contact
%a{:href => "mailto:contact@musiquely.com"} contact@musiquely.com

app/views/pages/contact.html.haml
%h1 Contact
%a{:href => 'mailto:contact@musiquely.com'} contact@musiquely.com

app/views/pages/dashboard.html.haml
%h1 Dashboard
- if current_user
  %p= "Welcome #{current_user.name}!"
  = link_to 'Playlists', playlists_path
- else
  %p Error, not logged in

app/views/pages/index.haml
.jumbotron
  %h1 Musiquely
  %p Micromanage your playlists

app/views/pages/index.html.haml
.jumbotron
  %h1 Musiquely
  %p Micromanage your playlists

app/views/playlists/index.html.haml
%h1 Playlists
%p
  = link_to 'Back to Dashboard', dashboard_path
  |
  = link_to 'Refresh', playlists_refresh_path
%table.table.table-striped
  - @playlists.each do |playlist|
    %tr
      %td= link_to playlist.name, playlist_path(playlist.spotify_id)
      %td= link_to 'Refresh', playlist_refresh_path(playlist.spotify_id)

app/views/playlists/show.html.haml
%h1= @playlist.name
%p= link_to 'Back to Playlists', playlists_path
%table.table.table-striped
  %tr
    %th #
    %th Track
    %th Artist
    %th Preview
  - @entries.each do |entry|
    %tr
      %td= entry.position
      %td= entry.track.name
      %td= entry.track.artist
      %td
        - unless (entry.track.preview_url == '')
          %audio{controls: true, preload: 'none'}
            %source{src: "#{entry.track.preview_url}", type: 'audio/mpeg'}